// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DotnetBackendSkeleton.Repositories;

#nullable disable

namespace DotnetBackendSkeleton.Migrations
{
    [DbContext(typeof(TodoItemContext))]
    [Migration("20230720135246_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("DotnetBackendSkeleton.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf554799-962b-4475-ad2a-484b0bdff859"),
                            Title = "Task 1",
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("3380ef7a-d5ea-476e-a622-24a6df5188a1"),
                            Title = "Task 2",
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("6662c961-f251-4545-9887-da0dba6605c1"),
                            Title = "Task 3",
                            status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
