version: '3.4'

services:
  dotnet-backend-skeleton:
    image: dotnet-backend-skeleton:1.0
    container_name: dotnet-backend-skeleton
    build:
      context: .
    environment:
      - Application__Name=Application
      - ASPNETCORE_URLS=http://+:80
      - Application__ConnectionString=${APPLICATION_CONNECTION_STRING}
      - Application__HttpClientAddress=${APPLICATION_HTTP_CLIENT_ADDRESS}
    ports:
      - "80"